# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/tom/clion-2016.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/tom/clion-2016.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tom/Documents/Coding/FTPL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tom/Documents/Coding/FTPL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/tom/clion-2016.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/tom/clion-2016.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tom/Documents/Coding/FTPL/CMakeFiles /home/tom/Documents/Coding/FTPL/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tom/Documents/Coding/FTPL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FTPL

# Build rule for target.
FTPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FTPL
.PHONY : FTPL

# fast build rule for target.
FTPL/fast:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/build
.PHONY : FTPL/fast

CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

.PHONY : CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

.PHONY : CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

.PHONY : CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

Types.o: Types.cpp.o

.PHONY : Types.o

# target to build an object file
Types.cpp.o:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/Types.cpp.o
.PHONY : Types.cpp.o

Types.i: Types.cpp.i

.PHONY : Types.i

# target to preprocess a source file
Types.cpp.i:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/Types.cpp.i
.PHONY : Types.cpp.i

Types.s: Types.cpp.s

.PHONY : Types.s

# target to generate assembly for a file
Types.cpp.s:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/Types.cpp.s
.PHONY : Types.cpp.s

cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.o: cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

.PHONY : cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.i: cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

.PHONY : cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.s: cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

.PHONY : cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/FTPL.dir/build.make CMakeFiles/FTPL.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FTPL"
	@echo "... CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... Types.o"
	@echo "... Types.i"
	@echo "... Types.s"
	@echo "... cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... cmake-build-debug/CMakeFiles/3.6.2/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

